// Builds a time-triggered table from a constraints file, and checks any
// table against the constraints it claims to satisfy.
//
// A developer tool, so it may use exceptions and std::print, which SPEC 7.1
// allows outside the data plane.

#include "volt/sched/schedule_checker.hpp"
#include "volt/sched/schedule_generator.hpp"

#include <yaml-cpp/yaml.h>

#include <cstdint>
#include <cstdio>
#include <filesystem>
#include <fstream>
#include <print>
#include <span>
#include <string>
#include <string_view>
#include <vector>

namespace {

using volt::sched::Exclusion;
using volt::sched::Precedence;
using volt::sched::ScheduleConstraints;
using volt::sched::ScheduledTask;
using volt::sched::ScheduleSlot;
using volt::sched::ScheduleTable;
using volt::sched::TaskId;

/// The files speak microseconds, which is what a person writing a schedule
/// thinks in; everything inside VOLT is nanoseconds.
constexpr std::int64_t kNanosecondsPerMicrosecond = 1'000;

/// `generate <file> -o <out>`: the output flag starts at the fourth word.
constexpr std::size_t kGenerateWithOutputWords = 5;

constexpr int kUsageError = 2;
constexpr int kInputError = 3;
constexpr int kUnsatisfiable = 4;
constexpr int kInvalidTable = 5;

[[nodiscard]] volt::core::Duration microseconds(const YAML::Node &node, const char *field) {
  return volt::core::Duration::from_us(node[field].as<std::int64_t>());
}

[[nodiscard]] ScheduleConstraints read_constraints(const std::string &path) {
  const YAML::Node document = YAML::LoadFile(path);
  ScheduleConstraints constraints;
  constraints.lane_count = document["lane_count"].as<std::uint32_t>();

  for (const YAML::Node &task : document["tasks"]) {
    constraints.tasks.push_back(ScheduledTask{.id = TaskId{task["id"].as<std::uint32_t>()},
                                              .name = task["name"].as<std::string>(),
                                              .period = microseconds(task, "period_us"),
                                              .wcet = microseconds(task, "wcet_us")});
  }
  if (document["precedences"]) {
    for (const YAML::Node &rule : document["precedences"]) {
      constraints.precedences.push_back(
          Precedence{.before = TaskId{rule["before"].as<std::uint32_t>()},
                     .after = TaskId{rule["after"].as<std::uint32_t>()},
                     .min_gap = microseconds(rule, "min_gap_us")});
    }
  }
  if (document["exclusions"]) {
    for (const YAML::Node &rule : document["exclusions"]) {
      constraints.exclusions.push_back(
          Exclusion{.first = TaskId{rule["first"].as<std::uint32_t>()},
                    .second = TaskId{rule["second"].as<std::uint32_t>()}});
    }
  }
  return constraints;
}

[[nodiscard]] ScheduleTable read_table(const std::string &path) {
  const YAML::Node document = YAML::LoadFile(path);
  ScheduleTable table;
  table.hyperperiod = microseconds(document, "hyperperiod_us");
  table.lane_count = document["lane_count"].as<std::uint32_t>();
  for (const YAML::Node &slot : document["slots"]) {
    table.slots.push_back(ScheduleSlot{.task = TaskId{slot["task"].as<std::uint32_t>()},
                                       .lane = slot["lane"].as<std::uint32_t>(),
                                       .offset = microseconds(slot, "offset_us"),
                                       .budget = microseconds(slot, "budget_us")});
  }
  return table;
}

void write_table(const ScheduleTable &table, const ScheduleConstraints &constraints,
                 const std::string &path) {
  std::ofstream out{path};
  std::print(out, "# Generated by tt_schedule_gen. Offsets are from the hyperperiod origin.\n");
  std::print(out, "hyperperiod_us: {}\n", table.hyperperiod.ns() / kNanosecondsPerMicrosecond);
  std::print(out, "lane_count: {}\n", table.lane_count);
  std::print(out, "slots:\n");
  for (const ScheduleSlot &slot : table.slots) {
    std::string_view name = "unknown";
    for (const ScheduledTask &task : constraints.tasks) {
      name = task.id == slot.task ? std::string_view{task.name} : name;
    }
    std::print(out, "  - task: {}\n    lane: {}\n    offset_us: {}\n    budget_us: {}\n",
               slot.task.value(), slot.lane, slot.offset.ns() / kNanosecondsPerMicrosecond,
               slot.budget.ns() / kNanosecondsPerMicrosecond);
    std::print(out, "    name: {}\n", name);
  }
}

void print_table(const ScheduleTable &table, const ScheduleConstraints &constraints) {
  std::print("hyperperiod {} us over {} lane(s), {} slots\n",
             table.hyperperiod.ns() / kNanosecondsPerMicrosecond, table.lane_count,
             table.slots.size());
  for (const ScheduleSlot &slot : table.slots) {
    std::string_view name = "unknown";
    for (const ScheduledTask &task : constraints.tasks) {
      name = task.id == slot.task ? std::string_view{task.name} : name;
    }
    std::print("  lane {}  {:>8} .. {:<8} us  {}\n", slot.lane,
               slot.offset.ns() / kNanosecondsPerMicrosecond,
               slot.end().ns() / kNanosecondsPerMicrosecond, name);
  }
}

[[nodiscard]] int generate(const std::string &constraints_path, const std::string &output_path) {
  const ScheduleConstraints constraints = read_constraints(constraints_path);
  const volt::core::expected<ScheduleTable> table = volt::sched::generate_schedule(constraints);
  if (!table.has_value()) {
    std::print(stderr, "no table satisfies these constraints (error {})\n",
               static_cast<unsigned>(table.error()));
    return kUnsatisfiable;
  }
  print_table(*table, constraints);
  if (!output_path.empty()) {
    write_table(*table, constraints, output_path);
    std::print("written to {}\n", output_path);
  }
  return 0;
}

[[nodiscard]] int check(const std::string &constraints_path, const std::string &table_path) {
  const ScheduleConstraints constraints = read_constraints(constraints_path);
  const ScheduleTable table = read_table(table_path);
  const volt::sched::ScheduleVerdict verdict = volt::sched::check_schedule(constraints, table);
  if (verdict.valid()) {
    std::print("table satisfies every constraint\n");
    return 0;
  }
  std::print(stderr, "invalid table: {}\n", volt::sched::to_string(verdict.defect));
  std::print(stderr, "  slot {} (and slot {} where a pair is involved)\n", verdict.slot_index,
             verdict.other_index);
  return kInvalidTable;
}

void usage() {
  std::print(stderr, "usage:\n");
  std::print(stderr, "  tt_schedule_gen generate <constraints.yaml> [-o <table.yaml>]\n");
  std::print(stderr, "  tt_schedule_gen check <constraints.yaml> <table.yaml>\n");
}

[[nodiscard]] int run(const std::vector<std::string> &arguments) {
  if (arguments.size() < 3) {
    usage();
    return kUsageError;
  }
  if (arguments[1] == "generate") {
    std::string output;
    if (arguments.size() >= kGenerateWithOutputWords && arguments[3] == "-o") {
      output = arguments[4];
    }
    return generate(arguments[2], output);
  }
  if (arguments[1] == "check" && arguments.size() >= 4) {
    return check(arguments[2], arguments[3]);
  }
  usage();
  return kUsageError;
}

} // namespace

int main(int argc, char **argv) {
  // Nothing escapes: the YAML reader throws on a malformed file, and a tool
  // that dies with a raw terminate message helps nobody debug their input.
  try {
    return run(std::vector<std::string>{argv, argv + argc});
  } catch (const std::exception &failure) {
    // fputs rather than std::print: a handler that can throw would leave
    // main throwing, which is the one thing main must not do.
    static_cast<void>(std::fputs("could not read the input: ", stderr));
    static_cast<void>(std::fputs(failure.what(), stderr));
    static_cast<void>(std::fputs("\n", stderr));
    return kInputError;
  } catch (...) {
    static_cast<void>(std::fputs("could not read the input\n", stderr));
    return kInputError;
  }
}
